[build]
  publish = "."
  command = ""

[build.environment]
  PHP_VERSION = "8.2"

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/public/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/public/:splat"
  status = 200
